title: State Courts Practice Directions
remote_theme: opengovsg/opendoc-theme
section_order:
  - State Courts Practice Directions
  - "Part I: Introduction"
  - "Part II: Originating Processes and Documents"
  - "Part III: Simplified Process for Civil Proceedings in the Magistrate’s Court"
  - "Part IIIA: “Documents-Only” Proceedings"   
  - "Part IV: Interlocutory and other Applications"
  - "Part V: Hearings via Skype"
  - "Part VI: Alternative Dispute Resolution"
  - "Part VII: Discovery and Inspection of Electronically Stored Documents"
  - "Part VIII: Evidence – Witnesses, Affidavits and Exhibits"
  - "Part IX: Fixing of Matters for Hearing"
  - "Part X: Documents and Authorities for use in Court"
  - "Part XI: Judgements and Orders"
  - "Part XII: Appeals"
  - "Part XIII: Electronic Filing Service"
  - "Part XIV: Execution Matters"
  - "Part XV: Bills of Costs for Taxation"
  - "Part XVI: General Matters"
  - "Part XVII: Criminal Matters"
  - "Part XVIII: Electronic Filing and Service for Criminal Proceedings"
  - "Part XIX: Community Disputes Resolution"
  - "Part XX: Employment Claims"
  - "Part XXI: Defamation Actions"
  - "Appendices"
google_analytics: UA-113717369-8
server_PROD: https://search.opendoc.sg
server_DEV: https://search.opendoc.sg
styling_options:
  primary_brand_color: '#9f0836'
  logo_path: /assets/logo-full.png
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/forms/govtech/5bc68139e3eea0000f2b1f8b
